name: Visual Regression (Chromatic)
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  chromatic:
    name: 'Gate D: Visual Regression'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - run: pnpm install --frozen-lockfile=false
      
      - name: Build Storybook
        run: pnpm build:storybook
      
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
          exitZeroOnChanges: false
          autoAcceptChanges: false
          onlyChanged: true
