name: Visual Regression (Chromatic)
on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  chromatic:
    name: 'Gate D: Visual Regression'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      - name: Neutralize project .npmrc if present
        run: mv .npmrc .npmrc.bak || true
      - name: Configure registries
        run: |
          npm config set registry https://registry.npmjs.org/
          npm config set @mgasic:registry https://npm.pkg.github.com/
          echo "//npm.pkg.github.com/:_authToken=${PACKAGES_TOKEN}" >> ~/.npmrc
        env:
          PACKAGES_TOKEN: ${{ secrets.PACKAGES_TOKEN }}
      - run: pnpm install --no-frozen-lockfile
      - name: Build Storybook
        run: pnpm build:storybook
      - name: Publish to Chromatic
        uses: chromaui/action@v1
        with:
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
          token: ${{ secrets.GITHUB_TOKEN }}
          storybookBuildDir: storybook-static
          exitZeroOnChanges: false
          autoAcceptChanges: false
          onlyChanged: true
